apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dwi-ws
  name: dwi-ws
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: dwi-ws
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: dwi-ws
    spec:
      containers:
      - env:
         - name: DB_HOSTNAME
           valueFrom:
              configMapKeyRef:
                key: DB_HOSTNAME
                name: dwiws-cfgmap
         - name: DB_NAME
           valueFrom:
              configMapKeyRef:
                key: DB_NAME
                name: dwiws-cfgmap
         - name: DB_PASSWORD
           valueFrom:
              configMapKeyRef:
                key: DB_PASSWORD
                name: dwiws-cfgmap
         - name: DB_PORT
           valueFrom:
              configMapKeyRef:
                key: DB_PORT
                name: dwiws-cfgmap
         - name: DB_USERNAME
           valueFrom:
              configMapKeyRef:
                key: DB_USERNAME
                name: dwiws-cfgmap      
#        - name: DB_HOSTNAME
#          value: mysql
#        - name: DB_NAME
#          value: IVRDB
#        - name: DB_PASSWORD
#          value: tosaporn
#        - name: DB_PORT
#          value: "3306"
#        - name: DB_USERNAME
#          value: ivrad
        image: tosaporn/dwi-backend:0.0.1-SNAPSHOT
        name: dwi-ws
        ports:
        - containerPort: 8100
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dwi-ws
  name: dwi-ws
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    io.kompose.service: dwi-ws
  sessionAffinity: None #CHANGE
  type: LoadBalancer