apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: image-dwi
  name: image-dwi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
