apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: tmp-output-bt
  name: tmp-output-bt
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
